kind: pipeline
type: docker
name: default
   
steps:    
  - name: clean
    image: mcr.microsoft.com/dotnet/framework/sdk:latest
    commands:
      - msbuild Database.sln -target:Clean
      
  - name: build
    image: mcr.microsoft.com/dotnet/framework/sdk:latest
    commands:
      - msbuild Database.sln -t:rebuild