kind: pipeline
type: docker
name: Project Build

steps:    
  - name: clean
    image: mcr.microsoft.com/dotnet/framework/aspnet:4.5
    commands:
      - dotnet clean Database.sln

  - name: build
    image: mcr.microsoft.com/dotnet/framework/aspnet:4.5
    commands:
      - dotnet build Database.sln -c Debug
     
      
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - pull_request
      - push