kind: pipeline
type: docker
name: IPM build
   
steps:    
  - name: clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - dotnet clean SampleDB/SampleDB.sln
      
  - name: build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
      - dotnet build SampleDB/SampleDB.sln
trigger:
  branch:
    include:
      - test
  event:
    include:
      - push
      - pull_request
      
---
kind: pipeline
type: docker
name: IPM deploy
   
steps:    
  - name: clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - dotnet clean SampleDB/SampleDB.sln
      
  - name: build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
      - dotnet build SampleDB/SampleDB.sln
      
  - name: Deploy to Azure SQL Database
    image: sijaymm/sqlpackage
    environment:
      SERVER_NAME:
        from_secret: SERVER_NAME
      DB_NAME:
        from_secret: DB_NAME
      USERNAME:
        from_secret: USERNAME
      PASSWORD:
        from_secret: PASSWORD
    commands:
      - sqlpackage.exe /TargetFile:"/drone/src/output_target.dacpac" /Action:Extract /tsn:$SERVER_NAME /tdn:$DB_NAME /tu:$USERNAME /tp:$PASSWORD

trigger:
  branch:
    include:
      - test
  event:
    include:
      - push
      - pull_request
