kind: pipeline
type: docker
name: default
   
steps:    
  - name: clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - dotnet clean Database/Database.sqlproj
      
  - name: build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
      - dotnet build Database/Database.sqlproj